# Generated by Django 4.2.13 on 2024-05-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
