# Generated by Django 4.2.13 on 2024-05-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(default='Asset', max_length=100),
        ),
        migrations.AddField(
            model_name='assettype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='name',
            field=models.CharField(default='AssetType', max_length=100),
        ),
    ]
