# Generated by Django 4.2.13 on 2024-06-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_cost_asset_name_assettype_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='units',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
    ]
