# Generated by Django 4.2.13 on 2024-06-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='specific_type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='name',
            field=models.CharField(default='AssetType', max_length=13),
        ),
    ]
